### PR TITLE
Bump PHP to 8.1 in 6.x images

### PR DESCRIPTION
**Pull request by edgarrmondragon**
PHP 8.2.0 was released 08 Dec 2022 (see https://www.php.net/releases/index.php).

This repo uses Renovate and that may already bump these automatically, so let me know if you're explicitly avoiding bumping the version.

EDIT: tests are failing, so maybe that's enough reason to punt the update 😅.

### CODE REVIEW

**Comment by martialblog** [comment]
Hi, I'm sure we can fix that somehow.

We also should check that LS 5 and 6 support PHP 8.2

**Comment by martialblog** [comment]
From the manual:

```
PHP version requirements:

    LS 6.x from PHP 7.4.x to 8.1.x
    LS 5.x from PHP 7.2.5 to 8.0.x
    LS 3.x from PHP 5.5.9 to 7.4.x
```

**Comment by edgarrmondragon** [comment]
The apache image test is failing even for 8.1 🤔

**Comment by martialblog** [comment]
Might just be some PHP dependencies. I can have look at it

**Comment by martialblog** [comment]
Seems as if marking some libraries as manually installed `ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so` is not working properly here. I'm investigating

**Comment by martialblog** [comment]
@edgarrmondragon I have fix in #178 

You should be able to rebase from master and everything should work.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon I have fix in #178
> 
> You should be able to rebase from master and everything should work.

@martialblog done!

**Comment by martialblog** [comment]
Awesome. All things green. I'll do some manual testing and then we should be good to go.

Thanks!

**Comment by martialblog** [comment]
Merged. Thanks @edgarrmondragon

**Pull request merged**
