### PR TITLE
Move config templates to var

### LINKED ISSUE #79: Tweak entrypoints.sh
Reuse `entrypoint.sh` to have coderepetition

### PR DESCRIPTION
**Pull request by JensHeinrich**
Fixes #79

### CODE REVIEW

**Comment by JensHeinrich** [comment]
This is a try for now, but it works

Basically:

- Move config templates into a variable
- Move the variables into reusable env-files in the project root

**Comment by JensHeinrich** [comment]
An alternative could be to make one `Dockerfile` and use targets

**Comment by jacksgt** [comment]
Hey, thanks for the effort.

I'm not really onboard with this change, but maybe I don't just don't understand the use case.
In my opinion, environment variables should be a simple as possible -- in the end they are just key-value strings, and should be treated as such.
If there is a need to dynamically entire files into the container, please use a [Kubernetes configmap](https://kubernetes.io/docs/concepts/configuration/configmap/), [Docker configs](https://docs.docker.com/engine/swarm/configs/) or simply mount a file into the container.

**Comment by JensHeinrich** [comment]
It was basically just my first idea on how to reduce the repeated code in the `entrypoint.sh` by moving the "templates" from a repeating hardcoded block in the shell files to the docker-compose files first (to be moved into a `.env` file shared by all yaml files


@martialblog suggested better Ressources now

**Comment by JensHeinrich** [comment]
Ok

**Comment by martialblog** [comment]
@JensHeinrich  no worries, every PR is welcome for discussion. I agree with @jacksgt though (trust me he's a Pro).

**Pull request closed without merging**
