### PR TITLE
Add suggestions from shellcheck

### PR DESCRIPTION
**Pull request by JensHeinrich**
This adds suggestions by [shellcheck](https://www.shellcheck.net/) to the entry point scripts and a few minor tweaks to use `sh` builtins instead of command

### CODE REVIEW

**Comment by martialblog** [comment]
Hey, thanks for the PR! I'll give it a review.

We can also add a shellcheck to the CI.

Cheers

**Comment by JensHeinrich** [comment]
Can do :)

**Comment by JensHeinrich** [comment]
Or rather feel free to do so, because I have no idea about github actions ^^

**Comment by JensHeinrich** [comment]
What I would like to add to the tweaking of the scripts would be to move the recurring parts into `function`-definitions to better see the differences between the different entry point scripts and make it easier to reuse the functions

**Comment by martialblog** [comment]
@JensHeinrich Thanks for the PR. Looks good. 

About the entrypoint, I'd love to have a single or maybe two entrypoint.sh (lts and latest), but symlink on the files and other mechanism didn't seemed right at the time. 

If you have any ideas for improvements, I'm open for discussions.

**Pull request merged**
