### PR TITLE
Add Variable to Ignore User-Agent in Logs

### PR DESCRIPTION
**Pull request by martialblog**
Reason behind this change is to ignore Health-Probes in the logs.

### CODE REVIEW

**Comment by jacksgt** [comment]
Do you want to keep this in entrypoint.sh or move it to a Dockerfile RUN?
I'm fine both ways, but I think the latter is preferable because the container image should be as immutable as possible (though we are far away from that, anyway).

**Comment by martialblog** [comment]
The idea was to provide a flexible option, so that people using something other than k8s can use it. 

I'm all for not having too many variables... maybe there's a better solution, got any ideas?

**Comment by jacksgt** [comment]
I would do exactly the same `sed` just as a Dockerfile `RUN`.
I think we can just have a bunch of ignored User-Agents "hardcoded" in the Docker image: Kube-probe and maybe whatever Nomad is using for [their check_restart stanzas](https://www.nomadproject.io/docs/job-specification/check_restart).
Should be good enough? Maybe I'm too pragmatic...

**Comment by jacksgt** [comment]
Actually, what do you think about this?
https://github.com/martialblog/helm-charts/pull/11
No need to modify the image at runtime.

**Comment by martialblog** [comment]
I thought about this and yeah hardcoding a set would be fine, the entrypoint is complex enough.

Then I thought about it some more... Why log the status code 200 in the first place? Why not disable the 200 codes by default and keep the rest. In production it's likely that there's a proxy in front of the application that logs requests anyways and if someone wants all the logs, they can still configure it.

**Comment by martialblog** [comment]
@jacksgt  how about this: https://github.com/martialblog/docker-limesurvey/pull/80/commits/974f8f86547a97835d365b2b0509d5e7e6b0ab7d

No variable, no sed magic, easy to understand and easy to extend :sunglasses:

**Comment by jacksgt** [comment]
Sure, I'm fine with that. Did you by any chance check which user-agent Nomad uses for healthchecks?

**Review by jacksgt — APPROVED** [review]

**Comment by martialblog** [comment]
I know Consul uses "Consul Health Check", not sure about Nomad, but I would hope something similar

**Pull request merged**
